name: ait_flutter_template

packages:
  - packages/**
  - utils/**
command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  build_runner:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build in the ODM example app.
    select-package:
      depends-on: "freezed"
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub --no-test-assets"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
