name: ait_flutter_template

packages:
  - packages/**
command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  build_runner:auth:
    run: |
      melos exec -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build in the ODM example app.
    select-package:
      scope: "*auth*"
