name: ait_flutter_template

packages:
  - packages/**
  - utils/**
command:
  bootstrap:
    usePubspecOverrides: true
scripts:
  build_runner:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run a build_runner build in the ODM example app.
    select-package:
      depends-on: "freezed"
  translate:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter pub run intl_utils:generate"
    description: Run a build_runner build in the ODM example app.
    select-package:
      depends-on: "intl_utils"
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub --no-test-assets"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
  test:all:
    run: melos run test --no-select
    description: Run `flutter test` for a specific package.
  coverage:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --coverage --no-test-assets"
    description: Run `flutter test coverage` for a specific package.
      - test
  coverage:all: melos run coverage --no-select
  gen_coverage: melos exec -- "E:\study\flutter\ait_flutter_template\ait_flutter_template\combine_coverage.sh"
  # gen_coverage:
  # exec: echo $MELOS_ROOT_PATH"
  # exec: echo $MELOS_ROOT_PATH"
