name: ait_flutter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
 sdk: ">=2.12.0 <3.0.0" 

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  json_serializable: ^6.1.3
  mocktail: ^0.3.0

dev_dependencies:
  analyzer: ^3.0.0
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  freezed: ^1.1.1
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
