name: ait_flutter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ait_const:
    path : 'packages/ait_const'
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_screenutil: ^5.5.4
  widgetbook: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
