name: common_dependency
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: "../../system/design_system"
  auth:
    path: "../../packages/auth"
  api:
    path: "../api"
  flutter_hooks: ^0.18.5+1
  equatable: ^2.0.5
  flutter_screenutil: ^5.5.4
  formz: ^0.4.1
  flutter_bloc: ^8.1.1
  extended_image: ^6.3.2
  dartz: ^0.10.1
  get_it: ^7.2.0
  boxy: ^2.0.6+2

dev_dependencies:
  freezed: ^2.1.1
  flutter_lints: ^2.0.1
  bloc_test: 9.1.0

  flutter_test:
    sdk: flutter

flutter:
